name: Release

on:
  push:
    tags:
    - v*.*.*

permissions:
  contents: write

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: RustReleaser Action
        uses: sakkke/rustreleaser-action@v9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
